// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8eXmIRTqnYAmdpuUhoNweNDGK4bFkvM',
    appId: '1:623143794290:web:d7b289dc61c37451c3f4eb',
    messagingSenderId: '623143794290',
    projectId: 'chat-app-96b0c',
    authDomain: 'chat-app-96b0c.firebaseapp.com',
    storageBucket: 'chat-app-96b0c.appspot.com',
    measurementId: 'G-L7514334QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjl2JbI9QC5Um5YeFuUEbtMftydwVxYU',
    appId: '1:623143794290:android:e75e5656c022d506c3f4eb',
    messagingSenderId: '623143794290',
    projectId: 'chat-app-96b0c',
    storageBucket: 'chat-app-96b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hpzjYME1l6QoJpo_LiB9UM5IwBNxafU',
    appId: '1:623143794290:ios:09a8d6aaffb996ecc3f4eb',
    messagingSenderId: '623143794290',
    projectId: 'chat-app-96b0c',
    storageBucket: 'chat-app-96b0c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hpzjYME1l6QoJpo_LiB9UM5IwBNxafU',
    appId: '1:623143794290:ios:09a8d6aaffb996ecc3f4eb',
    messagingSenderId: '623143794290',
    projectId: 'chat-app-96b0c',
    storageBucket: 'chat-app-96b0c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX8eXmIRTqnYAmdpuUhoNweNDGK4bFkvM',
    appId: '1:623143794290:web:3e81a3ac0a465e0fc3f4eb',
    messagingSenderId: '623143794290',
    projectId: 'chat-app-96b0c',
    authDomain: 'chat-app-96b0c.firebaseapp.com',
    storageBucket: 'chat-app-96b0c.appspot.com',
    measurementId: 'G-1DY2KZ56HW',
  );
}
